#!/bin/bash

# Fill the below access/secret keys appropriately
export AWS_ACCESS_KEY_ID=AKIAXXXXXXXXXXXXXXXX
export AWS_SECRET_ACCESS_KEY=uRXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX

DATADIR=data

[[ ! -f "$DATADIR" ]] && mkdir -p $DATADIR
